name: carrot-mapper-dev

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  web:
    image: carrot
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - $PWD/api:/api
    depends_on:
      - db
      - azurite

  nginx:
    image: nginx:latest
    # network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - azurite
