# Generated by Django 3.1.14 on 2022-04-28 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("RESTRICTED", "Restricted")],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dataset_admins",
                        related_query_name="dataset_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        related_query_name="dataset",
                        to="mapping.datapartner",
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dataset_editors",
                        related_query_name="dataset_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dataset_viewings",
                        related_query_name="dataset_viewing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
            },
        ),
        migrations.AddField(
            model_name="scanreport",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="scanreport_editors",
                related_query_name="scanreport_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scanreport",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="scanreport_viewings",
                related_query_name="scanreport_viewing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scanreport",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("RESTRICTED", "Restricted")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        related_query_name="project",
                        to="mapping.Dataset",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="projects",
                        related_query_name="project",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AddField(
            model_name="scanreport",
            name="parent_dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_reports",
                related_query_name="scan_report",
                to="mapping.dataset",
            ),
        ),
    ]
