# Generated by Django 4.2.13 on 2024-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_handmade_20220428_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreporttable',
            name='death_table',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
