# Generated by Django 4.2.13 on 2024-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_handmade_20220428_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanreport',
            name='status',
        ),
        migrations.AddField(
            model_name='scanreport',
            name='mapping_status',
            field=models.CharField(choices=[('PENDING', 'Mapping 0%'), ('INPRO25', 'Mapping 25%'), ('INPRO50', 'Mapping 50%'), ('INPRO75', 'Mapping 75%'), ('COMPLET', 'Mapping Complete'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=7),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='upload_status',
            field=models.CharField(choices=[('UPINPRO', 'Upload in Progress'), ('UPCOMPL', 'Upload Complete'), ('UPFAILE', 'Upload Failed')], default='UPINPRO', max_length=7),
        ),
    ]
