# Generated by Django 4.2.13 on 2024-10-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_handmade_20220428_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='scanreport',
            name='mapping_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mapping_status', to='mapping.mappingstatus'),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='upload_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upload_status', to='mapping.uploadstatus'),
        ),
    ]
