# Generated by Django 4.2.13 on 2024-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_scanreporttable_death_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanreporttable',
            name='death_table',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
