# Generated by Django 4.2.15 on 2024-11-27 14:13

from django.db import migrations, models
import django.db.models.deletion


def seeding_objects(apps, schema_editor):
    JobStage = apps.get_model("mapping", "JobStage")
    StageStatus = apps.get_model("mapping", "StageStatus")

    job_stages = [
        {"id": 1, "value": "UPLOAD_SCAN_REPORT", "display_name": "Upload Scan Report"},
        {
            "id": 2,
            "value": "BUILDING_FROM_DICT",
            "display_name": "Building concepts from OMOP Vocabs dictionary",
        },
        {
            "id": 3,
            "value": "REUSING_CONCEPTS",
            "display_name": "Reusing concepts from other scan reports",
        },
        {
            "id": 4,
            "value": "GENERATING_RULES",
            "display_name": "Generating mapping rules from available concepts",
        },
        {
            "id": 5,
            "value": "DOWNLOAD_RULES",
            "display_name": "Generate and download mapping rules JSON",
        },
    ]

    for stage in job_stages:
        JobStage.objects.create(
            id=stage["id"],
            value=stage["value"],
            display_name=stage["display_name"],
        )

    stage_statuses = [
        {
            "id": 1,
            "value": "IN_PROGRESS",
            "display_name": "The job stage is in progress",
        },
        {
            "id": 2,
            "value": "COMPLETED",
            "display_name": "The job stage has been completed",
        },
        {"id": 3, "value": "FAILED", "display_name": "The job stage has failed"},
    ]

    for status in stage_statuses:
        StageStatus.objects.create(
            id=status["id"],
            value=status["value"],
            display_name=status["display_name"],
        )


def unseeding_objects(apps, schema_editor):
    JobStage = apps.get_model("mapping", "JobStage")
    StageStatus = apps.get_model("mapping", "StageStatus")
    # Remove all objects
    JobStage.objects.all().delete()
    StageStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0005_auto_20241015_0900"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="StageStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.RunPython(seeding_objects, unseeding_objects),
        migrations.CreateModel(
            name="ScanReportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_report_id", models.IntegerField(null=True)),
                ("scan_report_table_id", models.IntegerField(null=True)),
                (
                    "stage",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="job_stage",
                        to="mapping.jobstage",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stage_status",
                        to="mapping.stagestatus",
                    ),
                ),
                ("details", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
