# Generated by Django 5.2.1 on 2025-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_auto_20241015_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreporttable',
            name='trigger_reuse',
            field=models.BooleanField(default=True),
        ),
    ]
