# Generated by Django 4.2.13 on 2024-10-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0005_auto_20241015_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanreporttable",
            name="death_table",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
