# Generated by Django 5.2.1 on 2025-07-10 20:16

import django.db.models.deletion
from django.db import migrations, models


def create_search_mapping_tool(apps, schema_editor):
    MappingTool = apps.get_model("mapping", "MappingTool")
    MappingTool.objects.create(name="Search", version="1.0")


def reverse_create_search_mapping_tool(apps, schema_editor):
    MappingTool = apps.get_model("mapping", "MappingTool")
    MappingTool.objects.filter(name="Search").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data", "__first__"),
        ("mapping", "0011_scanreport_upload_status_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingTool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Mapping Tool",
                "verbose_name_plural": "Mapping Tools",
            },
        ),
        migrations.RunPython(
            create_search_mapping_tool, reverse_create_search_mapping_tool
        ),
        migrations.CreateModel(
            name="MappingRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("score", models.FloatField()),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.concept"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mapping.mappingtool",
                    ),
                ),
            ],
        ),
    ]
