# Generated by Django 5.2.1 on 2025-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0010_scanreportconcept_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanreport",
            name="upload_status_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
