# Generated by Django 5.2.8 on 2026-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0014_alter_scanreportfield_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreporttable',
            name='death_table',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
