# Generated by Django 5.2.17 on 2026-08-17 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0015_scanreporttable_death_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_admins",
                related_query_name="project_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
