# Generated by Django 5.2.17 on 2026-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0017_dataset_description_project_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanreportconcept",
            name="creation_type",
            field=models.CharField(
                choices=[
                    ("M", "Manual"),
                    ("V", "Vocab"),
                    ("R", "Reuse"),
                    ("X", "Matched"),
                ],
                db_index=True,
                default="M",
                max_length=1,
            ),
        ),
    ]
