import os
from libs.enums import StorageType

storage_type = os.getenv("STORAGE_TYPE", StorageType.MINIO)
AIRFLOW_VAR_WASB_CONNECTION_STRING = os.getenv("AIRFLOW_VAR_WASB_CONNECTION_STRING", "")
AIRFLOW_VAR_MINIO_ENDPOINT = os.getenv("AIRFLOW_VAR_MINIO_ENDPOINT", "")
AIRFLOW_VAR_MINIO_ACCESS_KEY = os.getenv("AIRFLOW_VAR_MINIO_ACCESS_KEY", "")
AIRFLOW_VAR_MINIO_SECRET_KEY = os.getenv("AIRFLOW_VAR_MINIO_SECRET_KEY", "")
