# Generated by Django 3.1.5 on 2021-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localDB_name', models.CharField(max_length=256)),
                ('localDB_table', models.CharField(max_length=265)),
                ('localDB_column', models.CharField(max_length=256)),
                ('localDB_value', models.CharField(max_length=256)),
                ('term', models.CharField(max_length=256)),
            ],
        ),
    ]
