# Generated by Django 3.1.5 on 2021-01-04 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.localdb')),
            ],
        ),
    ]
