# Generated by Django 3.1.5 on 2021-01-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210104_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledvocab',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.localdb'),
        ),
    ]
