# Generated by Django 3.1.5 on 2021-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210104_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledvocab',
            name='term',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
