# Generated by Django 5.2.17 on 2026-08-18 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("scanreport", "Scan Report"), ("dataset", "Dataset")],
                        max_length=32,
                    ),
                ),
                ("scope_id", models.IntegerField()),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("mapping.added", "Mapping added"),
                            ("mapping.deleted", "Mapping deleted"),
                            ("rules.downloaded", "Rules downloaded"),
                            ("automap.ran", "Auto mapping ran"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_label", models.CharField(max_length=150)),
                ("object_type", models.CharField(blank=True, max_length=32)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope_type", "scope_id", "-occurred_at"],
                        name="idx_activitylog_scope",
                    )
                ],
            },
        ),
    ]
