# Generated by Django 5.2.17 on 2026-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="verb",
            field=models.CharField(
                choices=[
                    ("scanreport.uploaded", "Scan report uploaded"),
                    ("mapping.added", "Mapping added"),
                    ("mapping.deleted", "Mapping deleted"),
                    ("rules.downloaded", "Rules downloaded"),
                    ("automap.ran", "Auto mapping ran"),
                ],
                max_length=64,
            ),
        ),
    ]
