# Generated by Django 5.2.17 on 2026-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_log", "0002_alter_activitylog_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="verb",
            field=models.CharField(
                choices=[
                    ("scanreport.uploaded", "Scan report uploaded"),
                    ("scanreport.updated", "Scan report updated"),
                    ("dataset.updated", "Dataset updated"),
                    ("mapping.added", "Mapping added"),
                    ("mapping.deleted", "Mapping deleted"),
                    ("rules.export_requested", "Rules export requested"),
                    ("rules.downloaded", "Rules downloaded"),
                    ("automap.ran", "Auto mapping ran"),
                ],
                max_length=64,
            ),
        ),
    ]
