name: ci
on: [pull_request]

permissions:
  contents: read

jobs:
  format_python_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
          ref: ${{ github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run Ruff Checks
        uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf # v3.2.1
        with:
          args: "check --select I ."
      
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@39f75e526a505e26a302f8796977b50c13720edf # v3.2.1
        with:
          args: "format --check --diff"

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      RUNNER_ALLOW_RUNASROOT: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
      - name: Build the docker image
        working-directory: ./app
        run: docker build -f api/Dockerfile -t ccom-build:latest .
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
      - name: Install dependencies and build Next.js app
        run: |
          npm install
          npm run build
        working-directory: app/next-client-app
