# Generated by Django 5.2.17 on 2026-08-19 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mapping", "0017_dataset_description_project_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        max_length=19,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ORCID iD must be in the format 0000-0000-0000-0000.",
                                regex="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                            )
                        ],
                    ),
                ),
                (
                    "data_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        related_query_name="profile",
                        to="mapping.datapartner",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
